# Copyright 2015-2016 Jason Ozias
#
# This file is part of rl-sys.
#
# rl-sys is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# rl-sys is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with rl-sys.  If not, see <http://www.gnu.org/licenses/>.

language: rust
sudo: false
addons:
  apt:
    sources:
      - kalakris-cmake
    packages:
      - cmake
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - binutils-dev
rust:
  - stable
  - beta
  - nightly
os:
  - linux
matrix:
  allow_failures:
    - rust: nightly
before_script:
  - |
      pip install 'travis-cargo<0.2' --user &&
      export PATH=$HOME/.local/bin:$PATH
script:
  - |
      travis-cargo --only nightly build -- --features lint &&
      travis-cargo --only nightly test -- --features lint &&
      travis-cargo --skip nightly build &&
      travis-cargo --skip nightly test &&
      travis-cargo --only stable doc
after_success:
  - travis-cargo coveralls --no-sudo --verify
  - ./scripts/travis-doc-upload.sh
env:
  global:
    # override the default `--features unstable` used for the nightly branch (optional)
    - TRAVIS_CARGO_NIGHTLY_FEATURE=""
